### PR TITLE
Reverse the order of the panes in the main splitview

### PR DESCRIPTION
**Pull request by ipmcc**
I found the ordering of the panes to be non-intuitive (in fact for the first 10 minutes, I was there trying to drag and drop files into the search pane). Master/Detail relationships in MacOS UI generally have the master (here, the files list) on the left, and the detail (here, the property editing) on the right. The search box is an adjunct/helper for the property editing. I get that search is the "main feature", but it just doesn't make sense to me that it's on the left when you'll need to add files before it does anything meaningful. Cognitively, I normally process things from left to right. The app seems far more usable to me with the files panel on the left.  Since there's clearly inertia behind the current layout, it seemed like it would be a low-impedance approach to have this behavior be governed by a user default.

I also simplified the NSSplitViewDelegate implementation considerably.

### CODE REVIEW

**Comment by griff** [comment]
Actually I have been considering a redesign of MetaZ. The current look is because MetaZ started as a clone of MetaX and so I just copied the look from that verbatim.

What I had in mind was to rearrange the panes so that it goes (from left to right): files pane (and make that look like the itunes source list), search pane (with button to hide it) and last property editor.
The reason for considering this is because I feel it follows the master / details relationship more closely, since the property editor is really a combination of search result and selected files and search is based on the selected files.

What are your thoughts?

**Comment by stonematt** [comment]
this has bugged me for a long time.  I'd love it to look like a pipeline from left to right with 'candidates to update' -> actions to take -> completed updates (including an integrated queue) would make more sense

**Comment by ipmcc** [comment]
While I felt that the files panel being on the right was absolutely wrong, reinventing the whole UI is a big task with far more ambiguity. I'm not convinced that a source list is the right motif for the files list. It's not a "source list" so much as it is an "input queue". I think nominally, I would expect things to disappear from the input queue as they're edited. I don't normally think of Source Lists as getting modified by the app itself -- they're usually a read-only "projection" of some underlying data structure. Also source lists always seem to remind me of iTunes, and iTunes seems to be an app that people love to hate.

When I think about the workflow here, search is really a "helper" for the core work of "editing the metadata tags." Conceptually, you'd prefer not to have to search at all, right? You'd prefer for the app to magically fill in the tags with the exact right data! That's probably a tall order, but if MetaZ were somewhat more automatic -- in other words, better able to narrow down the search results and pick the right one on its own 'most of the time' -- then I could see moving the search results picker into a [popover](https://developer.apple.com/library/mac/documentation/userexperience/Conceptual/AppleHIGuidelines/Windows/Windows.html#//apple_ref/doc/uid/20000961-SW4). 

To focus those ideas a little, imagine this:  An "input" files pane on the left, a tag-editing pane in the middle, and move the work queue into the right pane of the main window. This way the workflow progresses logically left-to-right. Drag your input files into the app, and they would start on the left. You proceed to the next (middle) pane where you edit the tags (more in a second), and once you've edited the tags, you confirm the edits and the file would be removed from the list on the left and added as a work queue item on the right (and the work queue should probably be collapsible) If you need to make further edits, you should be able to select an un-started work queue item and move it back (to the left) for editing. 

Now, in terms of editing (and the search that supports it), when you drag in a bunch of files, the app should start a background queue picking apart any existing meta data (probably the file name in most cases) and running searches for each file.  When the user selects a file on the left, there should be a "Auto-Fill" button. If the app is confident (for whatever reason) that it's found the right answer, that button should just auto populate the form. If there's ambiguity, it should make a popover.  If you can forgive the ghetto-fabulous image editing, you could imagine that normally the screen looks like this: [Image](http://i.imgur.com/fwp7S.png) and then, if there is ambiguity, or when the user clicks on the disclosure part of the AutoFill button, you could show a popover like this: [Image](http://i.imgur.com/rHurd.png)

I'm trying to think of other apps that support a similar workflow elegantly, and I'm drawing a blank. Handbrake is a similar workflow, but its interface isn't really worth imitating in my opinion (despite being a fabulously useful app.)

But!  In the mean time, I feel like the simple changes I made in this pull request make MetaZ far more useful. I am content to use my locally built copy, but figured I'd try to contribute back.  Rebooting the UI would be a large undertaking -- this patch seems like a low-effort/high-reward option for the short term.

**Comment by ipmcc** [comment]
@stonematt: Glad I'm not the only one who was baffled by this. I mocked up some fake UI in my previous comment -- is that the kind of thing you were thinking of?

**Comment by griff** [comment]
@ipmcc you are right that redesigning the UI is a major undertaking and this patch makes MetaZ more useful. But I don't agree that there needs to be a preference for switching the locations of the files pane and search pane. I believe that we should just reverse the order and make that the only option. The order in your patch is more logical for newcomers and for existing users I don't believe it will cause will cause them any problems adjusting to the change. I believe that software should be opinionated and only have user preferences for vital things and making something as small as this into a user modifiable preference goes against that. So if you remove the preference I'll merge this.

I also propose that we start an issue to have the more general UI discussion. While I agree that adding some automatic searching and tagging would be an awesome features, if you add too much of it, you risk taking away control from the user. The sweet spot is magical and empowering to the user. And if you want total automation there is iDentify. One thing I dislike about your popover idea is that you lose the ability to view the data in the search result until after you have selected a result which is something I quite like.

**Comment by ipmcc** [comment]
I've updated this pull request per our discussion and removed the defaults setting, and brought the branch up to date with 1.0a13.

**Comment by ipmcc** [comment]
Woot! Thanks.

**Pull request merged**
