### PR TITLE
Fix/universal build of thirdparty binaries

### LINKED ISSUE #278: Not adding files to TV app
I've got the MetaZ preferences set correctly (never really change them) but lately I've noticed a tendency for MetaZ not to add processed files to the MacOS TV app. More confounding is the fact that it is inconsistent—sometimes it adds the files just fine, other times not at all, other times, some of them. I'm attaching a log file for anyone who might find it useful.

[MetaZ.log](https://github.com/user-attachments/files/17691954/MetaZ.log)

### PR DESCRIPTION
**Pull request by jmcintyre**
Update atomic parsley and mp4chaps to latest releases and use universal binary builds to that they work properly with both Intel and Apple Silicon Macs.
Relates to #278

### CODE REVIEW

**Comment by jmcintyre** [comment]
@griff  This shouldn't be committed yet. I need to test the output of the build process to make sure signing works with the new builds of these binaries. Unfortunately, the only way I say to test the process was to put in a pull request.

**Comment by jmcintyre** [comment]
@griff That didn't quite work out as I'd hoped. I didn't realize the tests didn't generate a binary that was saved for testing. I'm not sure the how best to validate this.

**Comment by jmcintyre** [comment]
Updated with changes to atom management and support for newer command changes in the current AtomicParsley

**Comment by griff** [comment]
We could change the build process to upload PR builds to the server where I used to host the website.

**Comment by griff** [comment]
I mean the server where I still host the website.

**Comment by griff** [comment]
When a PR is work in progress making it a draft might make sense. Don't know exactly how draft PR's work but we could test it.

**Comment by jmcintyre** [comment]
Switched to draft. If there is a way to modify the build process so we can get a look at the build artifacts without generating another official pre-release, I think that would be useful.

**Comment by jmcintyre** [comment]
There is an issue with the mp4chaps trying to load a library from my build location on other computers. I'll need to fix that.

**Comment by jmcintyre** [comment]
I redid the mp4chaps binary so it can run standalone.

**Comment by jmcintyre** [comment]
@griff, I have pretty high confidence in the change itself now. I'm running my locally built binary on multiple computers, both Intel and Apple Silicon. In that sense, it is ready for review, but I don't understand the code signing process enough to know whether the version built on the server will resign the command line executables. Otherwise, they will just be signed from my development build.

**Comment by griff** [comment]
The only thing signed right now is the Sparkle update bundle and that is done with a local key I just generated years and years ago. I have never joined the Apple Developer Program and so have never set up code signing for MetaZ.

I looked over the changes and if you are good with them I am fine with merging this PR.

**Comment by jmcintyre** [comment]
Alright, I'll post it and we'll see what happens.

**Pull request merged**
