### PR TITLE
Numeric sort the file list

### PR DESCRIPTION
**Pull request by jmcintyre**
Currently, when the file name column is sorted, it will sort items like the following: Item1, Item8, Item11 as:

Item1
Item11
Item8

This change modifies the column sort to use NSString's NSNumericSearch comparison instead of the default. The result is a Finder like sort of:

Item1
Item8
Item11

### CODE REVIEW

**Comment by griff** [comment]
It looked good so I have merged it.

And as per policy you have been given commit rights to the main repository.

**Comment by jmcintyre** [comment]
I'm glad it worked for you, and thank you for putting me on the project. I have a couple of 4 hour plane rides coming up this weekend. I'm hoping to get some work on the new tags done during that time.

I also have a long standing feature that I developed for myself that treats tv shows different from other types. When you put the show and season tags in, it automatically builds out the artist, album, album artist, and disc information as iTunes does for it's tv shows. I was wondering if you would be interested in this type of feature. I'd need to polish it up heavily, and I imagine you'd want to enable/disable it preferences. I find it extremely useful and time reducing. Does this idea interest you?

Jared

**Comment by griff** [comment]
On 19/03/2014, at 04.15, jmcintyre notifications@github.com wrote:

> I'm glad it worked for you, and thank you for putting me on the project. I have a couple of 4 hour plane rides coming up this weekend. I'm hoping to get some work on the new tags done during that time. 
> I am looking forward to reading the pull request.
> 
> I also have a long standing feature that I developed for myself that treats tv shows different from other types. When you put the show and season tags in, it automatically builds out the artist, album, album artist, and disc information as iTunes does for it's tv shows. I was wondering if you would be interested in this type of feature. I'd need to polish it up heavily, and I imagine you'd want to enable/disable it preferences. I find it extremely useful and time reducing. Does this idea interest you? 

Sure. Doing something like that has been something I have been meaning to do for some time. MetaZ already does a little of this for certain tags and in certain situations. e.g. when writing the tags MetaZ will write the episode to the track number and most search results will use the TV Show name for the artist tag if it is a tv result and the actors if it is a movie result.

I have been meaning to make a generalized implementation for this. What I was thinking was that some tags are linked to other tags (dependent on the video type) and the MetaEdits class should reflect this so that when you edit the TV show name for TV Show it will also show that value in the artist field unless the user has explicitly edited the artist field. That way it defaults the tags to being linked but the user can override this linking and they can see what is linked.

But if you have code that works now lets get that included in MetaZ.
- Brian

**Comment by jmcintyre** [comment]
The version I've written for TV doesn't who up in the UI and completely overrides what you've entered in the forms. I think it needs some improving before I'd be willing to push it out to users. I'll see what I can do to get something showing in the UI that makes it more useful.

Jared

**Pull request merged**
