### PR TITLE
Automatically Use iTunes TV Format

### PR DESCRIPTION
**Pull request by jmcintyre**
A new setting is added to the general preferences pane to enable the use of automatic iTunes TV metadata format when editing a video of type TV Show.

Artist = [Show]
Album Artist = [Show]
Album = [Show], Season [Season #]

When this feature is enabled the artist, album, and album artist fields cannot be manually changes from the format above.

### CODE REVIEW

**Comment by jmcintyre** [comment]
Griff, could you take a look at this pull request and let me know if you want me to make any changes to it? We discussed the idea several years ago, and while it isn't the generic solution you discussed, it is a real time saver when working with TV shows that will be imported into iTunes.

**Comment by griff** [comment]
I have looked a little and it looks ok. But the biggest problem I have is that I currently can't compile MetaZ myself and so can't release your changes. I have switched machine and haven't done any work with xcode since the last release of MetaZ which was done with my old machine.

**Comment by griff** [comment]
Could you rebase this? I have made some changes to develop so that hopefully Travis CI will be able to build this PR.

**Comment by jmcintyre** [comment]
Take a look at it now.

**Comment by jmcintyre** [comment]
I just did a bit more cleanup and removed two files that didn't need to be changed.

**Pull request merged**
